#include "AddProblemDialog.h"
#include "../models/ProblemDatabase.h"
#include <QMessageBox>

AddProblemDialog::AddProblemDialog(QWidget* parent)
    : QDialog(parent) {
    setWindowTitle("Add New Problem");
    setModal(true);
    resize(400, 300);
    
    setupUI();
}

void AddProblemDialog::setupUI() {
    mainLayout_ = new QVBoxLayout(this);
    
    // Form layout
    formLayout_ = new QFormLayout();
    
    // Title input
    titleEdit_ = new QLineEdit(this);
    titleEdit_->setPlaceholderText("e.g., Two Sum");
    formLayout_->addRow("Problem Title:", titleEdit_);
    
    // URL input
    urlEdit_ = new QLineEdit(this);
    urlEdit_->setPlaceholderText("https://leetcode.com/problems/...");
    formLayout_->addRow("LeetCode URL:", urlEdit_);
    
    // Difficulty selection
    difficultyCombo_ = new QComboBox(this);
    difficultyCombo_->addItem("Easy", static_cast<int>(Difficulty::Easy));
    difficultyCombo_->addItem("Medium", static_cast<int>(Difficulty::Medium));
    difficultyCombo_->addItem("Hard", static_cast<int>(Difficulty::Hard));
    formLayout_->addRow("Difficulty:", difficultyCombo_);
    
    // Category selection
    categoryCombo_ = new QComboBox(this);
    categoryCombo_->addItem("New", static_cast<int>(Category::New));
    categoryCombo_->addItem("Incomplete", static_cast<int>(Category::Incomplete));
    categoryCombo_->addItem("Completed", static_cast<int>(Category::Completed));
    formLayout_->addRow("Category:", categoryCombo_);
    
    mainLayout_->addLayout(formLayout_);
    
    // Button box
    buttonBox_ = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, this);
    mainLayout_->addWidget(buttonBox_);
    
    // Connect signals
    connect(buttonBox_, &QDialogButtonBox::accepted, this, &AddProblemDialog::onAccept);
    connect(buttonBox_, &QDialogButtonBox::rejected, this, &AddProblemDialog::onReject);
    
    // Focus on title input
    titleEdit_->setFocus();
}

void AddProblemDialog::onAccept() {
    if (!validateInput()) {
        return;
    }
    
    // Create new problem
    Problem problem(
        0, // ID will be auto-generated by database
        titleEdit_->text().trimmed(),
        urlEdit_->text().trimmed(),
        static_cast<Difficulty>(difficultyCombo_->currentData().toInt())
    );
    
    problem.setCategory(static_cast<Category>(categoryCombo_->currentData().toInt()));
    
    // Save to database
    if (ProblemDatabase::instance().addProblem(problem)) {
        accept();
    } else {
        QMessageBox::critical(this, "Error", "Failed to add problem to database!");
    }
}

void AddProblemDialog::onReject() {
    reject();
}

bool AddProblemDialog::validateInput() {
    QString title = titleEdit_->text().trimmed();
    QString url = urlEdit_->text().trimmed();
    
    if (title.isEmpty()) {
        QMessageBox::warning(this, "Validation Error", "Problem title cannot be empty!");
        titleEdit_->setFocus();
        return false;
    }
    
    if (url.isEmpty()) {
        QMessageBox::warning(this, "Validation Error", "LeetCode URL cannot be empty!");
        urlEdit_->setFocus();
        return false;
    }
    
    if (!url.startsWith("http://") && !url.startsWith("https://")) {
        QMessageBox::warning(this, "Validation Error", "Please enter a valid URL starting with http:// or https://");
        urlEdit_->setFocus();
        return false;
    }
    
    return true;
}

#include "AddProblemDialog.moc"